## Notebook for generating metal-solvent interface

**Created on 12th October; modified on 13th December, 2023**

In [1]:
import pandas as pd
import numpy as np
from ase.io import read, write
from ase.build import add_adsorbate
from ase import Atoms
from ase.visualize import view
from pymatgen.core import Structure, Lattice
import nglview as nv

In [2]:
%%bash
pwd
ls -ltr

/Users/riteshk/Library/CloudStorage/Box-Box/Research-postdoc/catalysis_water-conc-effect/DFT/Au-slab-100/ACN-water-1M
total 160
-rw-------@ 1 riteshk  staff  5918250 Aug 22  2022 wacn_nvt2.data
-rw-------@ 1 riteshk  staff  2252545 Oct  3  2022 config.pdb
-rw-------@ 1 riteshk  staff     9246 Dec 12 21:49 test_acn-water_121223_22142.pdb
-rw-------@ 1 riteshk  staff     8638 Dec 12 22:03 test_acn-water_121223_22142_.pdb
-rw-------@ 1 riteshk  staff     6196 Dec 13 10:25 test_acn-water_121223_0_.pdb
-rw-------@ 1 riteshk  staff     6196 Dec 13 11:13 test_acn-water_121223_0_mod.pdb
-rw-------@ 1 riteshk  staff     4220 Dec 13 11:26 test_acn-water_121223_0_m.vasp
-rw-------@ 1 riteshk  staff     3742 Dec 13 11:29 test_acn-water_121223_0_mod.vasp
-rw-------@ 1 riteshk  staff     3746 Dec 13 11:30 test_acn-water_121223_0_mod..vasp
-rw-------@ 1 riteshk  staff     3368 Dec 13 11:33 au_100_mod.vasp
-rw-------@ 1 riteshk  staff    78195 Dec 13 11:34 gen_solv-metal_struc.ipynb


In [3]:
pris_slab = read('au_100_mod.vasp')
pris_slab

Atoms(symbols='Au80', pbc=True, cell=[11.772411301206128, 11.772411301206128, 18.324351862])

In [4]:
nv.show_ase(pris_slab)

NGLWidget()

In [ ]:
# slab_pc_1 = read('au_100_mod_pc.vasp')
# nv.show_ase(slab_pc_1)

In [70]:
# solv_cluster = read('test_acn-water_121223_0_mod.vasp')
solv_cluster = read('test_acn-water_121223_0_nn.pdb')
view(solv_cluster)

In [7]:
nv.show_ase(solv_cluster)

NGLWidget()

In [56]:
print(solv_cluster.get_positions()[:,2].min())
print(solv_cluster.get_positions()[:,2].max())

6.758
17.228


In [62]:
print(solv_cluster.get_positions()[:,0].min())
print(solv_cluster.get_positions()[:,1].min())
print(solv_cluster.get_positions()[:,1].max())

17.125
7.222
17.522


In [52]:
# solv_cluster.rotate(-45, 'y', rotate_cell=False)
# view(solv_cluster)

In [71]:
solv_pos = solv_cluster.get_positions()
for i in range(len(solv_pos)):
    solv_pos[i,0] -= (17.0)
    solv_pos[i,1] -= (7.0)
    solv_pos[i,2] += (4.0)
print(solv_pos)
solv_pos[:,2].max()

[[ 1.086  8.515 18.698]
 [ 1.229  7.72  19.954]
 [ 0.969  9.13  17.706]
 [ 0.288  7.174 20.031]
 [ 2.009  6.997 19.712]
 [ 1.424  8.285 20.865]
 [ 9.063  7.516 19.338]
 [ 9.266  7.394 20.772]
 [ 8.766  7.669 18.243]
 [ 8.277  7.44  21.228]
 [ 9.659  6.469 21.193]
 [ 9.965  8.145 21.14 ]
 [ 2.882  5.257 12.722]
 [ 1.888  5.376 11.688]
 [ 3.639  5.073 13.596]
 [ 0.941  5.905 11.792]
 [ 2.239  5.822 10.758]
 [ 1.683  4.368 11.328]
 [ 8.073  5.947 15.285]
 [ 8.66   7.223 14.775]
 [ 7.721  4.927 15.708]
 [ 9.432  7.582 15.457]
 [ 9.146  7.084 13.81 ]
 [ 7.829  7.928 14.778]
 [10.492  3.869 19.238]
 [ 9.183  4.078 18.576]
 [11.516  3.665 19.763]
 [ 8.384  4.302 19.283]
 [ 9.262  4.883 17.846]
 [ 8.89   3.135 18.113]
 [ 6.201  2.722 13.434]
 [ 5.368  2.279 14.57 ]
 [ 6.907  3.062 12.585]
 [ 5.526  1.207 14.689]
 [ 5.851  2.699 15.452]
 [ 4.338  2.635 14.54 ]
 [ 5.515  6.961 19.166]
 [ 5.316  6.767 17.74 ]
 [ 5.715  7.126 20.312]
 [ 4.806  7.649 17.352]
 [ 6.24   6.602 17.186]
 [ 4.7    5.873 

21.228

In [72]:
# acn_cluster.set_positions = acn_pos
solv_cluster_ = Atoms(symbols=solv_cluster.get_chemical_symbols(), positions=solv_pos)
solv_cluster_.get_positions()[:,2]

array([18.698, 19.954, 17.706, 20.031, 19.712, 20.865, 19.338, 20.772,
       18.243, 21.228, 21.193, 21.14 , 12.722, 11.688, 13.596, 11.792,
       10.758, 11.328, 15.285, 14.775, 15.708, 15.457, 13.81 , 14.778,
       19.238, 18.576, 19.763, 19.283, 17.846, 18.113, 13.434, 14.57 ,
       12.585, 14.689, 15.452, 14.54 , 19.166, 17.74 , 20.312, 17.352,
       17.186, 17.642, 15.996, 14.933, 16.815, 14.124, 15.389, 14.529,
       19.617, 18.923, 20.123, 17.991, 19.671, 18.668, 14.916, 14.772,
       15.065, 15.458, 13.779, 14.726, 17.56 , 16.306, 18.513, 15.751,
       16.593, 15.63 , 12.782, 13.692, 12.197, 12.456, 11.743, 12.685,
       11.915, 11.955, 12.285])

In [59]:
pris_slab.cell[2][2] = 23.0
pris_slab

Atoms(symbols='Au80', pbc=True, cell=[11.772411301206128, 11.772411301206128, 23.0])

In [39]:
## not working => don't use
# pris_slab_ = pris_slab
# add_adsorbate(pris_slab_, acn_cluster, height=2.5)

In [73]:
adsorbed_slab_sym = pris_slab.get_chemical_symbols() + solv_cluster_.get_chemical_symbols()
adsorbed_slab_pos = np.concatenate([pris_slab.get_positions(), solv_cluster_.get_positions()], axis=0)
adsorbed_slab = Atoms(symbols=adsorbed_slab_sym, positions=adsorbed_slab_pos, cell=pris_slab.cell, pbc=True)
view(adsorbed_slab)

In [15]:
adsorbed_slab_sym
type(adsorbed_slab)

ase.atoms.Atoms

In [74]:
dist_all = adsorbed_slab.get_all_distances().ravel()
dist_all

array([0.        , 2.943103  , 5.886206  , ..., 1.00058283, 1.63434085,
       0.        ])

In [75]:
# dist_all.sort()
dist_all_ = list(set(dist_all))
dist_all_.sort()

In [76]:
dist_all_ ## -> looks okay

[0.0,
 0.9992036829395687,
 0.9998469882937081,
 1.0002649648968012,
 1.000297455760038,
 1.0003004548634373,
 1.000582830154506,
 1.0893768861142596,
 1.0894007527076544,
 1.0895030977468576,
 1.089571475397553,
 1.0895737698751726,
 1.0895751465594279,
 1.0896398487573793,
 1.0897091355036008,
 1.0897683240028586,
 1.0897765826076462,
 1.0898050284339826,
 1.089811451582336,
 1.089818333484989,
 1.0898793511210298,
 1.0899160518131665,
 1.0899399066003574,
 1.089966054517297,
 1.0899729354438112,
 1.090033485724176,
 1.0900683464810828,
 1.0900899045491617,
 1.0900958673437848,
 1.0901495310277396,
 1.0901816362423253,
 1.0901999816547399,
 1.0902146577624054,
 1.0903857115718263,
 1.0906268839525275,
 1.0906539322809958,
 1.0907034427377595,
 1.090730489167697,
 1.0907405741055023,
 1.0908661696101856,
 1.1448331756199233,
 1.1507853839878184,
 1.1553514616773533,
 1.158979292308538,
 1.1611688077105768,
 1.1686817359743384,
 1.17080357020296,
 1.1730208864295637,
 1.174964254775438

In [77]:
pris_slab.cell.array

array([[11.7724113,  0.       ,  0.       ],
       [ 0.       , 11.7724113,  0.       ],
       [ 0.       ,  0.       , 23.       ]])

In [78]:
# write('au_100_mod_acn_ase.vasp', adsorbed_slab)
adsorbed_slab.get_number_of_atoms()

/Users/riteshk/codes/miniconda3/envs/mdanalysis/lib/python3.8/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
  warnings.warn('Use get_global_number_of_atoms() instead',


155

In [82]:
# adsorbed_slab_pym = Structure(pris_slab.cell.array, adsorbed_slab.get_chemical_symbols(), adsorbed_slab.get_scaled_positions()) ## pymatgen structure object
adsorbed_slab_pym = Structure(pris_slab.cell.array, adsorbed_slab.get_chemical_symbols(), adsorbed_slab.get_positions()) ## pymatgen structure object
adsorbed_slab_pym

Structure Summary
Lattice
    abc : 11.772411301206128 11.772411301206128 23.0
 angles : 90.0 90.0 90.0
 volume : 3187.5623604296125
      A : 11.772411301206128 0.0 0.0
      B : 0.0 11.772411301206128 0.0
      C : 0.0 0.0 23.0
    pbc : True True True
PeriodicSite: Au (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Au (34.65, 0.0, 0.0) [2.943, 0.0, 0.0]
PeriodicSite: Au (69.29, 0.0, 0.0) [5.886, 0.0, 0.0]
PeriodicSite: Au (103.9, 0.0, 0.0) [8.829, 0.0, 0.0]
PeriodicSite: Au (0.0, 34.65, 0.0) [0.0, 2.943, 0.0]
PeriodicSite: Au (34.65, 34.65, 0.0) [2.943, 2.943, 0.0]
PeriodicSite: Au (69.29, 34.65, 0.0) [5.886, 2.943, 0.0]
PeriodicSite: Au (103.9, 34.65, 0.0) [8.829, 2.943, 0.0]
PeriodicSite: Au (0.0, 69.29, 0.0) [0.0, 5.886, 0.0]
PeriodicSite: Au (34.65, 69.29, 0.0) [2.943, 5.886, 0.0]
PeriodicSite: Au (69.29, 69.29, 0.0) [5.886, 5.886, 0.0]
PeriodicSite: Au (103.9, 69.29, 0.0) [8.829, 5.886, 0.0]
PeriodicSite: Au (0.0, 103.9, 0.0) [0.0, 8.829, 0.0]
PeriodicSite: Au (34.65, 103.9, 0.0)

In [83]:
adsorbed_slab_pym.to(filename='au_100_mod_acn-w_pym_abs.vasp', fmt='poscar')

ignore below...

In [50]:
def gen_espresso_input(type='relax', ase_obj=Atoms, filename=None, **kwargs):
    filename_ = filename + '.in'
    f = open(filename_, 'w')
    if type == 'relax':
        f.write("&CONTROL\n")
        f.write("  calculation = 'relax'\n")
        f.write("  forc_conv_thr =   1.0000000000d-02\n")
        f.close()
#   outdir = '.'
#   prefix = 'au_dmso'
#   pseudo_dir = '.'
#   tprnfor = .true.
#   tstress = .true.
#   restart_mode = 'restart'
#   verbosity = 'high'
# /
# &SYSTEM
#   degauss =   0.015
#   ecutwfc = 33
#   ecutrho = 330
#   ibrav = 0
#   nat = 74
#   nosym = .false.
#   ntyp = 5
#   occupations = 'smearing'
#   smearing = 'gaussian'
# /
# &ELECTRONS
#   conv_thr =   1.0000000000d-6
#   electron_maxstep = 80
#   mixing_beta =   4.0000000000d-01
# /
# &IONS
#   ion_positions = 'default'
#   ion_dynamics = 'bfgs'
# /
# ATOMIC_SPECIES
# Au     196.966569  Au.pbe-n-kjpaw_psl.1.0.0.UPF
# S      32.065 S.pbe-n-kjpaw_psl.1.0.0.UPF
# O      15.9994 O.pbe-n-kjpaw_psl.0.1.UPF
# H      1.00794 H.pbe-kjpaw_psl.1.0.0.UPF
# C      12.0107 C.pbe-n-kjpaw_psl.1.0.0.UPF")

In [51]:
gen_espresso_input(filename='tt.in')

In [26]:
def convert_mol_ratio_solvent_ratio(mol_ratio, smiles_list, densities=None):
    """
    mol_ratio: list of mol ratio of each component
    densities: list of densities of each component
    """
    if densities is None:
        densities = [1.0 for i in range(len(mol_ratio))]
    else:
        assert len(mol_ratio) == len(densities) == len(smiles_list)
    mw_list = [rdMolDescriptors.CalcExactMolWt(Chem.MolFromSmiles(smiles)) for smiles in smiles_list]
    mass_list = [mw * mol for mw, mol in zip(mw_list, mol_ratio)]
    volume_list = [mass / density for mass, density in zip(mass_list, densities)]
    volume_ratio = [str(vol) + ':' for vol in volume_list]
    return mw_list, volume_ratio

In [11]:
convert_mol_ratio_solvent_ratio([1,2], ['COC(=O)OC', 'C(C(F)(F)F)OCC(F)(F)F'], densities=[1.069, 1.404]) ## DMC, BTFE

([90.031694052, 182.016634068], ['84.22048087184285:', '259.28295451282054:'])

In [33]:
# convert_mol_ratio_solvent_ratio([7.5,4.8], ['C1COC(=O)O1', 'CCOC(=O)OC'], densities=[1.321, 1.006]) ## EC, EMC
convert_mol_ratio_solvent_ratio([3,7], ['C1COC(=O)O1', 'CCOC(=O)OC'], densities=[1.321, 1.006]) ## EC, EMC

([88.016043988, 104.047344116], ['199.8850355518547:', '723.9874839085487:'])

In [31]:
convert_mol_ratio_solvent_ratio([3.2,2.6], ['C(C(C(F)F)(F)F)OC(C(F)F)(F)F', 'C1CCCO1'], densities=[1.537228, 0.89]) ## TTE, THF

([232.013440508, 72.057514876], ['482.97520577663175:', '210.5050996377528:'])

In [32]:
convert_mol_ratio_solvent_ratio([1,3], ['CCOP(=O)(OCC)OCC', 'C(C(F)(F)F)OCC(F)(F)F'], densities=[1.537228, 0.89]) ## TEP, BTFE

([182.07079559, 182.016634068], ['118.44098311376061:', '613.5392159595506:'])

In [13]:
## reduce the ratio by using common highest factor -> 84.22048087184285/259.28295451282054


0.32482073891085067

In [24]:
def convert_mass_ratio_solvent_ratio(mass_ratio, densities=None):
    """
    mass_ratio: list of mass ratio of each component
    densities: list of densities of each component
    """
    if densities is None:
        densities = [1.0 for i in range(len(mass_ratio))]
    else:
        assert len(mass_ratio) == len(densities)
    # mw_list = [rdMolDescriptors.CalcExactMolWt(Chem.MolFromSmiles(smiles)) for smiles in smiles_list]
    volume_list = [mass / density for mass, density in zip(mass_ratio, densities)]
    volume_ratio = [str(vol) + ':' for vol in volume_list]
    return volume_ratio

In [25]:
convert_mass_ratio_solvent_ratio([4,6], [1.321, 1.006]) ## EC, EMC
convert_mass_ratio_solvent_ratio([3,7], [1.321, 1.006]) ## EC, EMC

['2.2710068130204393:', '6.958250497017892:']

In [6]:
rdMolDescriptors.CalcExactMolWt(Chem.MolFromSmiles('COCCOC')) ## DME
rdMolDescriptors.CalcExactMolWt(Chem.MolFromSmiles('C(C(C(F)F)(F)F)OC(C(F)F)(F)F')) ## TTE
rdMolDescriptors.CalcExactMolWt(Chem.MolFromSmiles('[Li+].[N-](S(=O)(=O)F)S(=O)(=O)F ')) ## LiFSA

186.93968547000003

In [ ]:
density_DME = 0.867